/**
 * `getRelName` is a function that extracts the name of a relation from a relation URL.
 * It does this by splitting the URL by '/' and returning the last element of the resulting array.
 *
 * @param {string} RelUrl - The relation URL.
 * @returns {string} - The name of the relation.
 */
export class Problem {
  type: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;

  /**
   * Constructs a new `Problem` instance.
   *
   * @param {string} type - A URI reference that identifies the problem type.
   * @param {string} title - A short, human-readable summary of the problem type.
   * @param {number} status - The HTTP status code generated by the origin server for this occurrence of the problem.
   * @param {string} [detail] - A human-readable explanation specific to this occurrence of the problem.
   * @param {string} [instance] - A URI reference that identifies the specific occurrence of the problem.
   */
  constructor(type: string, title: string, status: number, detail?: string | null, instance?: string | null) {
    this.type = type;
    this.title = title;
    this.status = status;
    this.detail = detail;
    this.instance = instance;
  }
}

/**
 * `problemMediaType` is a constant that represents the media type for problem details as defined in RFC 7807.
 */
export const problemMediaType = 'application/problem+json';
